import { Inter } from "next/font/google";
// import "@tremor/react/dist/esm/tremor.css";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const font = Inter({
    weight: ["300", "400", "600"],
    subsets: ["latin"],
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html
            lang="en"
            color-scheme="light"
        >
            <body className={font.className}>{children}</body>
        </html>
    );
}
